language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
deploy:
  skip_cleanup: true
  local_dir: public
  keep-history: true
  on:
    branch: main
before_script:
  - "yarn add global  gatsby"
  - "yarn install"
script:
  - "yarn test"
