language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
deploy:
  local_dir: public
  keep-history: true
  on:
    branch: main
before_script:
  - "npm i -g gatsby"
  - "npm i"
script:
  - "npm run test"
